max_width = 120
hard_tabs = true
tab_spaces = 4
newline_style = "Unix"
indent_style = "Block"
use_small_heuristics = "Default"
wrap_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
comment_width = 100
format_strings = true
normalize_comments = true
hex_literal_case = "Upper"
imports_layout = "Mixed"
match_block_trailing_comma = true
edition = "2021"
style_edition = "2024"
trailing_comma = "Vertical"
reorder_impl_items = true
space_before_colon = false
space_after_colon = true
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
use_field_init_shorthand = true
trailing_semicolon = true
reorder_imports = true
reorder_modules = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
type_punctuation_density = "Wide"
spaces_around_ranges = false
binop_separator = "Front"
remove_nested_parens = true
combine_control_expr = true
short_array_element_width_threshold = 10
overflow_delimited_expr = false
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never"
force_multiline_blocks = false
fn_params_layout = "Tall"
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
inline_attribute_width = 0
format_generated_files = true
merge_derives = true
use_try_shorthand = false
force_explicit_abi = true
condense_wildcard_suffixes = false
color = "Auto"
required_version = "1.8.0"
unstable_features = false
disable_all_formatting = false
skip_children = false
show_parse_errors = true
error_on_line_overflow = false
error_on_unformatted = false
ignore = []
emit_mode = "Files"
