.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dji_fpv_video_tool 1  "dji_fpv_video_tool 0.1.0" 
.SH NAME
dji_fpv_video_tool \- A tool to manipulate DJI video files and generate OSD frames from FPV.WTF .osd files
.SH SYNOPSIS
\fBdji_fpv_video_tool\fR [\fB\-l\fR|\fB\-\-log\-level\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
A tool to manipulate DJI video files and generate OSD frames from FPV.WTF .osd files
.SH OPTIONS
.TP
\fB\-l\fR, \fB\-\-log\-level\fR=\fILOG_LEVEL\fR [default: info]

.br
[\fIpossible values: \fRoff, error, warn, info, debug, trace]
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information
.SH SUBCOMMANDS
.TP
dji_fpv_video_tool\-display\-osd\-file\-info(1)
Displays information about the specified OSD file
.TP
dji_fpv_video_tool\-generate\-overlay\-frames(1)
Generates OSD overlay frames
.TP
dji_fpv_video_tool\-generate\-overlay\-video(1)
Generates OSD overlay video
.TP
dji_fpv_video_tool\-cut\-video(1)
Cut video file
.TP
dji_fpv_video_tool\-fix\-video\-audio(1)
Fixes DJI Air Unit video audio sync and/or volume
.TP
dji_fpv_video_tool\-transcode\-video(1)
Transcodes video file optionally burning OSD onto it
.TP
dji_fpv_video_tool\-play\-video\-with\-osd(1)
Play video using MPV video player with OSD by overlaying transparent OSD video in real time
.TP
dji_fpv_video_tool\-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v0.1.0
