.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH remove-audio-stream 1  "remove-audio-stream " 
.SH NAME
remove\-audio\-stream \- Remove the audio stream from a video file
.SH SYNOPSIS
\fBremove\-audio\-stream\fR [\fB\-P\fR|\fB\-\-ffmpeg\-priority\fR] [\fB\-y\fR|\fB\-\-overwrite\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIINPUT_VIDEO_FILE\fR> [\fIOUTPUT_VIDEO_FILE\fR] 
.SH DESCRIPTION
Remove the audio stream from a video file
.PP
The video track is copied directly without re\-encoding
.SH OPTIONS
.TP
\fB\-P\fR, \fB\-\-ffmpeg\-priority\fR \fI<FFMPEG_PRIORITY>\fR

.TP
\fB\-y\fR, \fB\-\-overwrite\fR
overwrite output file if it exists
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fIINPUT_VIDEO_FILE\fR>
input video file path
.TP
[\fIOUTPUT_VIDEO_FILE\fR]
output video file path
