.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH generate-overlay-video 1  "generate-overlay-video " 
.SH NAME
generate\-overlay\-video \- Generate an OSD overlay video to be displayed over another video
.SH SYNOPSIS
\fBgenerate\-overlay\-video\fR [\fB\-v\fR|\fB\-\-target\-video\-file\fR] [\fB\-\-hide\-regions\fR] [\fB\-\-hide\-items\fR] [\fB\-\-start\fR] [\fB\-\-end\fR] [\fB\-r\fR|\fB\-\-target\-resolution\fR] [\fB\-s\fR|\fB\-\-scaling\fR] [\fB\-n\fR|\fB\-\-no\-scaling\fR] [\fB\-\-min\-margins\fR] [\fB\-\-min\-coverage\fR] [\fB\-f\fR|\fB\-\-font\-dir\fR] [\fB\-i\fR|\fB\-\-font\-ident\fR] [\fB\-o\fR|\fB\-\-frame\-shift\fR] [\fB\-c\fR|\fB\-\-codec\fR] [\fB\-y\fR|\fB\-\-overwrite\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIOSD_FILE\fR> [\fIVIDEO_FILE\fR] 
.SH DESCRIPTION
Generate an OSD overlay video to be displayed over another video
.PP
This command generates a transparent video with the OSD frames rendered from the specified WTF.FPV OSD file. The generated video can then be used to play an FPV video with OSD without having to burn the OSD into the video.
.PP
If you specify a target resolution with \-\-target\-resolution or a video file to read the resolution from with \-\-target\-video\-file then the kind of tiles (HD/SD) to use and whether to use scaling or not will be decided to best match the target video resolution and to get the best OSD sharpness. If neither of these options are specified no scaling will be used and the kind of tiles used will be the native kind of tiles corresponding to the kind of OSD layout read from the FPV.WTF .osd file.
.PP
VP8 or VP9 codecs can be selected with the \-\-codec option. Files generated with the VP9 codec are smaller but also it is roughly twice as slow as encoding with the VP8 codec which is already unfortunately pretty slow.
.PP
Fonts are loaded either from the directory specified with the \-\-font\-dir option or from the directory found in the environment variable FONTS_DIR or if neither of these are available it falls back to the `fonts` directory inside the current directory.
.PP
NOTE: unfortunately this is very slow right now because only a handful of video formats support transparency and their encoders are very slow
.SH OPTIONS
.TP
\fB\-v\fR, \fB\-\-target\-video\-file\fR=\fITARGET_VIDEO_FILE\fR
use the resolution from the specified video file to decide what kind of tiles (SD/HD) would best fit and also whether scaling should be used when in auto scaling mode
.TP
\fB\-\-hide\-regions\fR=\fIREGIONS\fR
hide rectangular regions from the OSD

The parameter is a `;` separated list of regions.{n} The format for a region is: <left_x>,<top_y>[:<width>x<height>]{n} If the size is not specified it will default to 1x1
.TP
\fB\-\-hide\-items\fR=\fIITEM_NAMES\fR
hide items from the OSD

Available items (font variant: name list):
  \- Ardupilot: gpslat, gpslon, alt, short+code, long+code
  \- INAV: gpslat, gpslon, alt
.TP
\fB\-\-start\fR=\fI[HH:]MM:SS\fR
start timestamp
.TP
\fB\-\-end\fR=\fI[HH:]MM:SS\fR
end timestamp
.TP
\fB\-r\fR, \fB\-\-target\-resolution\fR=\fI720p 720p4:3 1080p 1080p4:3 <width>x<height>\fR
resolution used to decide what kind of tiles (SD/HD) would best fit and also whether scaling should be used when in auto scaling mode
.TP
\fB\-s\fR, \fB\-\-scaling\fR=\fISCALING\fR
force using scaling, default is automatic
.TP
\fB\-n\fR, \fB\-\-no\-scaling\fR=\fINO_SCALING\fR
force disable scaling, default is automatic
.TP
\fB\-\-min\-margins\fR=\fIhorizontal:vertical\fR [default: 20:20]
minimum margins to decide whether scaling should be used and how much to scale
.TP
\fB\-\-min\-coverage\fR=\fIpercent\fR [default: 90]
minimum percentage of OSD coverage under which scaling will be used if \-\-scaling/\-\-no\-scaling options are not provided
.TP
\fB\-f\fR, \fB\-\-font\-dir\fR=\fIdirpath\fR
path to the directory containing font sets
.TP
\fB\-i\fR, \fB\-\-font\-ident\fR=\fIident\fR
force using this font identifier when loading fonts, default is automatic
.TP
\fB\-o\fR, \fB\-\-frame\-shift\fR=\fIframes\fR
Shift the output by that number of frames. Use this option to sync the OSD to a particular video
.TP
\fB\-c\fR, \fB\-\-codec\fR=\fICODEC\fR [default: vp8]

.br
[\fIpossible values: \fRvp8, vp9]
.TP
\fB\-y\fR, \fB\-\-overwrite\fR=\fIOVERWRITE\fR
overwrite output file if it exists
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information (use `\-h` for a summary)
.TP
<\fIOSD_FILE\fR>
path to FPV.WTF .osd file
.TP
[\fIVIDEO_FILE\fR]
path of the video file to generate
