.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH fix-video-audio 1  "fix-video-audio " 
.SH NAME
fix\-video\-audio \- Fix a DJI Air Unit video\*(Aqs audio sync and/or volume
.SH SYNOPSIS
\fBfix\-video\-audio\fR [\fB\-s\fR|\fB\-\-sync\fR] [\fB\-v\fR|\fB\-\-volume\fR] [\fB\-P\fR|\fB\-\-ffmpeg\-priority\fR] [\fB\-y\fR|\fB\-\-overwrite\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIINPUT_VIDEO_FILE\fR> [\fIOUTPUT_VIDEO_FILE\fR] 
.SH DESCRIPTION
Fix a DJI Air Unit video\*(Aqs audio sync and/or volume
.PP
If the output video file is not provided the output video will be written in the same directory as the input video with the same file name with suffix `_fixed_audio`
.PP
Note that fixing the audio/video sync will only work if the start of the original video from the DJI FPV air unit has NOT been cut off.
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-sync\fR
fix audio sync only
.TP
\fB\-v\fR, \fB\-\-volume\fR
fix audio volume only
.TP
\fB\-P\fR, \fB\-\-ffmpeg\-priority\fR \fI<FFMPEG_PRIORITY>\fR

.TP
\fB\-y\fR, \fB\-\-overwrite\fR
overwrite output file if it exists
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fIINPUT_VIDEO_FILE\fR>
input video file path
.TP
[\fIOUTPUT_VIDEO_FILE\fR]
output video file path
