.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hd_fpv_video_tool 1  "hd_fpv_video_tool 2.1.0" 
.SH NAME
hd_fpv_video_tool \- A software tool to manipulate video files and OSD files recoded with the DJI and Walksnail Avatar FPV systems
.SH SYNOPSIS
\fBhd_fpv_video_tool\fR [\fB\-l\fR|\fB\-\-log\-level\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
hd_fpv_video_tool is a command line tool for manipulating video files and OSD files recorded with the DJI and Walksnail Avatar FPV systems
.PP
Author: Michel Pastor <shellixyz@gmail.com>
.PP
Each command is aliased to the concatenation of the first letter of each word of the command{n} Example: the `generate\-overlay\-frames` command is aliased to `gof`
.SH OPTIONS
.TP
\fB\-l\fR, \fB\-\-log\-level\fR \fI<LOG_LEVEL>\fR [default: info]

.br
[\fIpossible values: \fRoff, error, warn, info, debug, trace]
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
hd_fpv_video_tool\-display\-osd\-file\-info(1)
Display information about the specified OSD file
.TP
hd_fpv_video_tool\-generate\-overlay\-frames(1)
Generate a transparent overlay frame sequence as PNG files from a .osd file
.TP
hd_fpv_video_tool\-generate\-overlay\-video(1)
Generate an OSD overlay video to be displayed over another video
.TP
hd_fpv_video_tool\-cut\-video(1)
Cut a video file without transcoding by specifying the desired start and/or end timestamp
.TP
hd_fpv_video_tool\-fix\-video\-audio(1)
Fix a DJI Air Unit video\*(Aqs audio sync and/or volume
.TP
hd_fpv_video_tool\-transcode\-video(1)
Transcode a video file, optionally burning the OSD onto it
.TP
hd_fpv_video_tool\-play\-video\-with\-osd(1)
Play a video with OSD by overlaying a transparent OSD video in real time
.TP
hd_fpv_video_tool\-splice\-videos(1)
Splice videos files together
.TP
hd_fpv_video_tool\-add\-audio\-stream(1)
Add a silent audio stream to a video file
.TP
hd_fpv_video_tool\-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v2.1.0
