.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH display-profiles 1  "display-profiles " 
.SH NAME
display\-profiles \- Display available transcode profiles
.SH SYNOPSIS
\fBdisplay\-profiles\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Display available transcode profiles
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
