.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH splice-videos 1  "splice-videos " 
.SH NAME
splice\-videos \- Splice videos files together
.SH SYNOPSIS
\fBsplice\-videos\fR [\fB\-y\fR|\fB\-\-overwrite\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIINPUT_VIDEO_FILES\fR] <\fIOUTPUT\fR> 
.SH DESCRIPTION
Splice videos files together
.SH OPTIONS
.TP
\fB\-y\fR, \fB\-\-overwrite\fR
overwrite output file if it exists
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIINPUT_VIDEO_FILES\fR]
input video files
.TP
<\fIOUTPUT\fR>
output video file path
