.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH play-video-with-osd 1  "play-video-with-osd " 
.SH NAME
play\-video\-with\-osd \- Play a video with OSD by overlaying a transparent OSD video in real time
.SH SYNOPSIS
\fBplay\-video\-with\-osd\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIVIDEO_FILE\fR> [\fIOSD_VIDEO_FILE\fR] 
.SH DESCRIPTION
Play a video with OSD by overlaying a transparent OSD video in real time
.PP
You can generate a compatible OSD overlay video file with the `generate\-overlay\-video` command.
.PP
If the <OSD_VIDEO_FILE> argument is not provided it will try to use the file with the same base name as the <VIDEO_FILE> argument with suffix `_osd` and with `webm` extension.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fIVIDEO_FILE\fR>

.TP
[\fIOSD_VIDEO_FILE\fR]

