.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH display-osd-file-info 1  "display-osd-file-info " 
.SH NAME
display\-osd\-file\-info \- Display information about the specified OSD file
.SH SYNOPSIS
\fBdisplay\-osd\-file\-info\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIOSD_FILE\fR> 
.SH DESCRIPTION
Display information about the specified OSD file
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
<\fIOSD_FILE\fR>

