#!/usr/bin/sh

set -e

MAN_PAGES_DIR="man_pages"

echo -e "\e[1m\e[33mRunning tests\e[0m\e[0m\n"
cargo nextest run

echo -e "\n\e[1m\e[33mUpdating man pages\e[0m\e[0m\n"
rm -f "$MAN_PAGES_DIR"/*
cargo run -- generate-man-pages
git add "$MAN_PAGES_DIR"

echo
