name: Cargo Build & Test
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Required on GitHub; wrkflw will emulate this
      - uses: actions/checkout@v4

      # Everything else happens inside the Rust container
      - name: Build & test in Rust container
        uses: docker://rust:1-bookworm
        with:
          args: >
            bash -lc "
              apt-get update &&
              apt-get install -y
                ffmpeg libavformat-dev libavutil-dev libavfilter-dev
                libavdevice-dev libva-dev clang pkg-config &&
              cargo build --verbose &&
              cargo test --verbose
            "

