name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Required on GitHub; wrkflw will emulate it locally (you'll see that log line)
      - uses: actions/checkout@v4

      # Everything below runs inside the Rust image with a real shell
      - name: Build & test in Rust container
        uses: docker://rust:1-bookworm
        with:
          args: >
            bash -lc "
              apt-get update &&
              apt-get install -y
                ffmpeg libavformat-dev libavutil-dev libavfilter-dev
                libavdevice-dev libva-dev clang pkg-config &&
              cargo build --verbose &&
              cargo test --verbose
            "

